# Generated by Django 4.1.7 on 2023-03-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sovellus', '0003_postaus_kuva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postaus',
            name='kuva',
            field=models.ImageField(null=True, upload_to='blogi/kuvat'),
        ),
    ]
